plugins {
    id 'com.android.application'
}

android {
    namespace 'com.eagleai.generated.uyeleri_uyelik_durumunu_odeme'
    compileSdk 34

    defaultConfig {
        applicationId 'com.eagleai.generated.uyeleri_uyelik_durumunu_odeme'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
}
